const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync('webapp/index.html','utf8');
const code=html.split('<script>')[1].split('</script>')[0].replace(/gercekVeriyiYukle\(\);\s*$/,'');
const ctx=vm.createContext({console,Date,Intl,Map,Number,JSON,document:{getElementById:()=>({})}});
vm.runInContext(code,ctx);
const rendered=ctx.ortakAiGoster({karar:'IZLE',ai_score:72,confidence:65,kisa_gerekce:'<script>evil</script>',piyasa_rejimi:'YATAY',katkilar:{haber:2,makro:-1,sektor:3},updated_at:new Date().toISOString()});
for(const value of ['IZLE','72','65','Haber/KAP','Makro','Sektör','YATAY','Son güncelleme'])assert.ok(rendered.includes(value),value);
assert.ok(!rendered.includes('<script>evil'));
assert.ok(ctx.ortakAiGoster(null).includes('henüz yok'));
assert.ok(ctx.ortakAiGoster({updated_at:'2020-01-01T00:00:00+03:00'}).includes('ESKİ'));
assert.ok(html.includes('document.hidden || refreshing'));
assert.ok(html.includes('showGunIciTop10(true)'));
assert.ok(html.includes('showTop10(true)'));
assert.ok(html.includes('ortakAiGoster(data.ai_ozet)'));
assert.ok(html.includes('cloudDurumYenile()'));
assert.ok(html.includes('id="cloudStatus"'));
assert.ok(rendered.includes('Piyasa breadth'));
assert.ok(rendered.includes('Sektör relatif güç'));
console.log('Cloud UI visibility/freshness/escaping smoke passed');
