const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const html=fs.readFileSync('webapp/index.html','utf8');const code=html.split('<script>')[1].split('</script>')[0].replace(/gercekVeriyiYukle\(\);\s*$/,'');const target={innerHTML:'',textContent:'',style:{display:'block'}};const ctx=vm.createContext({console,Date,Intl,Map,Number,JSON,document:{getElementById:()=>target}});vm.runInContext(code,ctx);let checks=0;function check(v,msg){assert.ok(v,msg);checks++;}
const doc={engine_version:'MARKET_REGIME_V1',enabled:true,as_of:'2026-10-08T18:15:00+03:00',regime:'BULL',regime_score:72,regime_confidence:86,breadth_state:'STRONG',advancing_count:421,declining_count:273,valid_stock_count:700,above_sma20_pct:64,above_sma50_pct:57,risk_state:'NORMAL',advance_decline_ratio:1.5,advance_decline_net:148,up_volume_pct:71,down_volume_pct:29,new_high_count:10,new_low_count:3,index_trend:'POSITIVE',index_momentum:'POSITIVE',index_volatility:'NORMAL',market_open:false,data_age:30,reasons:['<img src=x onerror=alert(1)>'],warnings:['<script>bad</script>']};
let view=ctx.piyasaContextGoster(doc);for(const s of ['Piyasa Durumu','Pozitif','72/100','86/100','Güçlü','421','273','64,0%','57,0%','Normal'])check(view.summary.includes(s),s);
for(const s of ['Piyasa Kapalı','A/D oranı','71,0%','29,0%','Yeni yüksek','Endeks trend','Volatilite','Veri zamanı','&lt;img','&lt;script'])check(view.details.includes(s),s);check(!view.details.includes('<img'));
for(const [k,v] of Object.entries({STRONG_BULL:'Güçlü Pozitif',BULL:'Pozitif',NEUTRAL:'Nötr',BEAR:'Negatif',STRONG_BEAR:'Güçlü Negatif'}))check(ctx.piyasaContextGoster({...doc,regime:k}).summary.includes(v),k);
for(const [k,v] of Object.entries({VERY_STRONG:'Çok Güçlü',STRONG:'Güçlü',NEUTRAL:'Nötr',WEAK:'Zayıf',VERY_WEAK:'Çok Zayıf'}))check(ctx.piyasaContextGoster({...doc,breadth_state:k}).summary.includes(v),k);
for(const [k,v] of Object.entries({LOW:'Düşük',NORMAL:'Normal',HIGH:'Yüksek',EXTREME:'Çok Yüksek'}))check(ctx.piyasaContextGoster({...doc,risk_state:k}).summary.includes(v),k);
check(ctx.piyasaContextGoster({...doc,stale:true}).summary.includes('Eski veri'));check(ctx.piyasaContextGoster({enabled:false}).summary.includes('Devre dışı'));check(ctx.piyasaContextGoster(null).summary.includes('alınamıyor'));check(ctx.piyasaContextGoster({engine_version:'MARKET_REGIME_V1'}).summary.includes('—'));
(async()=>{const {chromium}=require('playwright');const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{const page=await browser.newPage({viewport:{width:430,height:932},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));let report=doc,failed=false;
await page.route('https://bist.test/**',route=>{const path=new URL(route.request().url()).pathname;if(path==='/')return route.fulfill({contentType:'text/html',body:html});let data={};if(path==='/api/market-context'){if(failed)return route.fulfill({status:503,body:'{}'});data=report;}else if(path==='/health')data={ana_motor:{healthy:true}};else if(path.endsWith('bist_data.json'))data={hisseler:[],updated_at:doc.as_of};return route.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
await page.goto('https://bist.test/');await page.waitForFunction(()=>document.getElementById('marketContextSummary').textContent.includes('72/100'));check(await page.locator('#marketContextCard').isVisible());await page.locator('#marketContextSummary').click();check((await page.locator('#marketContextDetails').textContent()).includes('Piyasa Kapalı'));check(await page.locator('#marketContextDetails img').count()===0);
const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:getComputedStyle(document.getElementById('homePage')).overflowY}));check(geometry.scroll<=geometry.width,JSON.stringify(geometry));check(geometry.overflow==='auto');report={...doc,stale:true};await page.evaluate(()=>piyasaContextYenile());check((await page.locator('#marketContextSummary').textContent()).includes('Eski veri'));report={enabled:false};await page.evaluate(()=>piyasaContextYenile());check((await page.locator('#marketContextSummary').textContent()).includes('Devre dışı'));failed=true;await page.evaluate(()=>piyasaContextYenile());check((await page.locator('#marketContextSummary').textContent()).includes('alınamıyor'));check(errors.length===0,errors.join(';'));
}finally{await browser.close()}console.log('MARKET_REGIME_UI_OK: '+checks+' assertions, Turkish mappings, mobile mock HTTP, freshness, feature-off, safe text');})().catch(e=>{console.error(e);process.exitCode=1});
